# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6646d2004701589ce339e2ffe4cac96d61a98e83c2107f93f6aec8c70dff6e5b8ea668ade0d1f43e96093212f9e18f566df80f75aa6c8248119c16c866e0ab06

test:
  secret_key_base: b1887c1cc0cc44ea48b518b8e9de8cebd38659f78d9d33d4f5ed3a315473d35424dc1d11b08af843e6486a7e70f91af23f643659ddb959f104589b02a22575ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
